#!/bin/bash
VER=0.1a
##
# paperwallet generator
# ---
# see https://github.com/BloodyNora/VerusPaperWallet for details
##  

##
# defaults
##

# show balance in figures
SHOW_BALANCE=0

# show balance in words
SHOW_BALANCE_WORDS=1

# encrypt private keys
ENCRYPT_KEY=1

# prepopulate the variable
VERUSID_REQUIRED_SIGNATURES=1

# RPC defaults
RPCUSER="verus"
RPCPASS="verus"
RPCHOST="127.0.0.1"
RPCPORT="27486"

# default notes
NOTES=In\ posterum\ veritas\ \&ndash\;\ in\ \<span\ class=\"font-size-35\ font-sourcesanspro\"\>verus\</span\>\ sanitas.

# default qrencode options, FFFFFF00 -> white with 0 alpha (thus transparent).
QRENCODE_OPTIONS="-tSVG --svg-path -lM --rle -m0 --background=FFFFFF00"
QRENCODE_OPTIONS_BW="-tSVG -lM --rle -m0 --background=FFFFFF00"

# default output file
OUTFILE="./out.html"

##
# check prerequisites
##

# qrencode
QRENCODE=$(which qrencode)
[ -z ${QRENCODE} ] && {
    echo "qrencode not found, exiting"
    exit 1
}

# openssl
OPENSSL=$(which openssl)
[ -z ${OPENSSL} ] && {
    echo "openssl not found, exiting" 1>&2
    exit 1
}

# awk
AWK=$(which awk)
[ -z ${AWK} ] && {
    echo "awk not found, exiting" 1>&2
    exit 1
}

# curl
CURL=$(which curl)
[ -z ${CURL} ] && {
    echo "curl not found, exiting" 1>&2
    exit 1
}

# jq
JQ=$(which jq)
[ -z ${JQ} ] && {
    echo "jq not found, exiting" 1>&2
    exit 1
}

# bc
BC=$(which bc)
[ -z ${BC} ] && {
    echo "bc not found, exiting" 1>&2
    exit 1
}

# chromium
CHROMIUM=$(which chromium)
[ -z ${CHROMIUM} ] && {
    echo "chromium not found - displaying & printing the paperwallet may be broken on other browsers."
    echo "See https://www.chromium.org/Home for chromium info and download links."
}

##
# version info
# ---
##
print_version(){
    echo "Verus Paper Wallet v${VER}"
    echo "See https://github.com/BloodyNora/VerusPaperWallet for details"
    echo "(c) 2021 ff. 0x03/BloodyNora"
    exit 1
}

##
# usage notice
# ---
##
print_usage(){
    echo "Usage: paperwallet OPTION... [FILE]..."
    echo "Generate a Paperwallet using the specified options and output to FILE."
    echo ""
    echo "Note that unless you use the '-d' option the input isn't validated against a"
    echo "live running verus daemon but instead just copied over verbatim after some sanity checks."
    echo ""
    echo "With no --outfile specified the output will always be written to"
    echo ""
    echo "    \"${OUTFILE}\""
    echo ""
    echo "overwriting previous contents in the process. Unless you specify empty notes,"
    echo "by using '--notes=\" \"' or '--notes \" \"' the default comment will be used:"
    echo ""
    echo "Only long options have (mandatory) arguments."
    echo "  -b                                    toggle balance display"
    echo "  -d                                    get all info from verusd (specify only \"--address\"),"
    echo "                                        also see the RPC options below"
    echo "  -e                                    disable encryption of private key"
    echo "  -m                                    generate monochrome SVG data only,"
    echo "                                        use this with older qrencode versions, i.e. on Ubuntu"
    echo "  --address ADDRESS                     primary address to use for paperwallet"
    echo "  --balance 12345.231132                balance to use for paperwallet"
    echo "  --key PRIVATEKEY                      private key to use for paperwallet"
    echo "  --notes NOTES                         shell escaped comment to put into paperwallet"
    echo "  --outfile OUTFILE                     file to write resulting paperwallet to,"
    echo "                                        defaults to \"${OUTFILE}\""
    echo "  --passphrase PASSPHRASE               passphrase to encrypt private key with"
    echo "  --rpc-user                            RPC username (default: ${RPCUSER})"
    echo "  --rpc-pass                            RPC password (default: ${RPCPASS})"
    echo "  --rpc-host                            RPC hostname (default: ${RPCHOST})"
    echo "  --rpc-port                            RPC port (default: ${RPCPORT})"
    echo "  --verusid-friendlyname FRIENDLYNAME   friendlyname to display for verusid"
    echo "  --verusid-zaddress ZADDRESS           zaddress to display for verusid"
    echo "  --verusid-taddress TADDRESS           taddress(es) associated with verusid,"
    echo "                                        specify multiple times if needed."
    echo "  --verusid-required-signatures NUM     minimum number of signatures needed"
    echo ""
    echo "  --help     display this help and exit"
    echo "  --version  output version information and exit"
    echo ""
    echo "Documentation:     <https://github.com/BloodyNora/VerusPaperWallet/>"
    echo "Verus online help: <https://wiki.verus.io/>"
    echo ""
    exit 1;
}

##
# getopt
# ---
# see https://dustymabe.com/2013/05/17/easy-getopt-for-a-bash-script/
# and https://bl.ocks.org/magnetikonline/22c1eb412daa350eeceee76c97519da8
# and 'man 1 getopt'
##
ARGUMENT_LIST="bdehmv"
LONG_ARGUMENT_LIST=(
    "notes"
    "address"
    "balance"
    "rpc-user"
    "rpc-pass"
    "rpc-host"
    "rpc-port"    
    "verusid-friendlyname"
    "verusid-zaddress"
    "verusid-taddress"
    "verusid-required-signatures"
    "key"
    "passphrase"
    "outfile"
)

# read arguments
OPTIONS=$(getopt \
    --longoptions "$(printf "%s:," "${LONG_ARGUMENT_LIST[@]}")",version,help \
    --name "$(basename "$0")" \
    --options "${ARGUMENT_LIST}" \
    -- "$@"
)

# if getopt returns 0 sum ting wong
[ ${?} -eq 0 ] || { 
    echo "Invalid options given, exiting."
    exit 1
}

eval set -- "${OPTIONS}"
while true; do
    case "$1" in
    -b)
        SHOW_BALANCE=1
        ;;
    -d)
        MODE="daemon"
        ;;
    -e)
        ENCRYPT_KEY=0
        ;;
    -m)
        QRENCODE_OPTIONS="${QRENCODE_OPTIONS_BW}"
        ;;
    -v|--version)
        print_version
        exit 1
        ;;
    -h|--help)
        print_usage
        exit 1
        ;;  
    --address)
        shift;
        ADDRESS="${1}"
        ;;
    --balance)
        shift;
        # set "show balance" flag
        SHOW_BALANCE=1
        # https://unix.stackexchange.com/questions/465583/what-does-cut-return-if-the-specified-field-does-not-exist
        BALANCE="${1}.0"
        ;;
    --key)
        shift;
        KEY="${1}"
        ;;
    --notes)
        shift;
        NOTES="${1}"
        ;;
    --outfile)
        shift;
        OUTFILE="${1}"
        ;;
    --passphrase)
        shift;
        PASSPHRASE="${1}"
        ;;
    --rpc-user)
        shift;
        RPCUSER="${1}"
        ;;
    --rpc-pass)
        shift;
        RPCPASS="${1}"
        ;;
    --rpc-host)
        shift;
        RPCHOST="${1}"
        ;;
    --rpc-port)
        shift;
        RPCPORT="${1}"
        ;;
    --verusid-friendlyname)
        shift;
        VERUSID_FRIENDLYNAME="${1}"
        ;;
    --verusid-zaddress)
        shift;
        VERUSID_ZADDRESS="${1}"
        ;;
    --verusid-taddress)
        shift;
        VERUSID_TADDRESS="${VERUSID_TADDRESS} ${1}"
        VERUSID_TADDRESS=$(echo ${VERUSID_TADDRESS}|xargs)
        ;;
    --verusid-required-signatures)
        shift;
        VERUSID_REQUIRED_SIGNATURES=${1}
        ;;
    --)
        shift
        break
        ;;
    esac
    shift
done

[ -z "${ADDRESS}" ] && { 
    echo "No address specified, exiting."
    exit 0;
}

get_qr_svg(){
    STRING="${1}"
    QRCODE=$(${QRENCODE} ${QRENCODE_OPTIONS} -o- "${STRING}")
    echo "${QRCODE}"
}

rpc_isvalid(){
	USER=$1
	PASS=$2
	HOST=$3
	PORT=$4
	ADDR=$5
    ISVALID=$(${CURL} -X POST -u ${USER}:${PASS} --data-binary \
    "{\"jsonrpc\": \"1.0\", \"id\": \"paperwallet\", \"method\": \"validateaddress\", \"params\": [\"${ADDR}\"]}" \
    -H 'content-type: application/json;' \
    http://${HOST}:${PORT} 2>/dev//null | ${JQ} -r .result.isvalid)

	[ "${ISVALID}" == "true" ] && return 0 || return 1
}

rpc_isvalid_z(){
    USER=$1
    PASS=$2
    HOST=$3
    PORT=$4
    ADDR=$5
    ISVALID=$(${CURL} -X POST -u ${USER}:${PASS} --data-binary \
    "{\"jsonrpc\": \"1.0\", \"id\": \"paperwallet\", \"method\": \"z_validateaddress\", \"params\": [\"${ADDR}\"]}" \
    -H 'content-type: application/json;' \
    http://${HOST}:${PORT} 2>/dev//null | ${JQ} -r .result.isvalid)

    [ "${ISVALID}" == "true" ] && return 0 || return 1
}

rpc_getbalance(){
    USER=$1
    PASS=$2
    HOST=$3
    PORT=$4
    ADDR=$5
	BALANCE=$(${CURL} -X POST -u ${USER}:${PASS} --data-binary \
    "{\"jsonrpc\": \"1.0\", \"id\": \"paperwallet\", \"method\": \"getaddressbalance\", \"params\": [{\"addresses\":[\"${ADDR}\"]}]}" \
    -H 'content-type: application/json;' \
    http://${HOST}:${PORT} 2>/dev//null | ${JQ} -r .result.balance)
    
    echo $(echo "scale=8;${BALANCE}/100000000"|${BC})
    [ -z ${BALANCE} ] && return 0 || return 1
}

rpc_getbalance_z(){
    USER=$1
    PASS=$2
    HOST=$3
    PORT=$4
    ADDR=$5
	BALANCE=$(${CURL} -X POST -u ${USER}:${PASS} --data-binary \
    "{\"jsonrpc\": \"1.0\", \"id\": \"paperwallet\", \"method\": \"z_getbalance\", \"params\": [\"${ADDR}\"]}" \
    -H 'content-type: application/json;' \
    http://${HOST}:${PORT} 2>/dev//null | ${JQ} -r .result)
    
    echo ${BALANCE}
    [ -z ${BALANCE} ] && return 0 || return 1
}

rpc_exportkey(){
    USER=$1
    PASS=$2
    HOST=$3
    PORT=$4
    ADDR=$5
	KEY=$(${CURL} -X POST -u ${USER}:${PASS} --data-binary \
    "{\"jsonrpc\": \"1.0\", \"id\": \"paperwallet\", \"method\": \"dumpprivkey\", \"params\": [\"${ADDR}\"]}" \
    -H 'content-type: application/json;' \
    http://${HOST}:${PORT} 2>/dev//null | ${JQ} -r .result)
    
    echo ${KEY}
    [ -z ${KEY} ] && return 0 || return 1
}

rpc_exportkey_z(){
    USER=$1
    PASS=$2
    HOST=$3
    PORT=$4
    ADDR=$5
	KEY=$(${CURL} -X POST -u ${USER}:${PASS} --data-binary \
    "{\"jsonrpc\": \"1.0\", \"id\": \"paperwallet\", \"method\": \"z_exportkey\", \"params\": [\"${ADDR}\"]}" \
    -H 'content-type: application/json;' \
    http://${HOST}:${PORT} 2>/dev//null | ${JQ} -r .result)
    
    echo ${KEY}
    [ -z ${KEY} ] && return 0 || return 1
}

rpc_getidentity(){
    USER=$1
    PASS=$2
    HOST=$3
    PORT=$4
    ADDR=$5
    JSON=$(${CURL} -X POST -u ${USER}:${PASS} --data-binary \
    "{\"jsonrpc\": \"1.0\", \"id\": \"paperwallet\", \"method\": \"getidentity\", \"params\": [\"${ADDR}\"]}" \
    -H 'content-type: application/json;' \
    http://${HOST}:${PORT} 2>/dev//null | ${JQ} -r .result)

    VERUSID_REQUIRED_SIGNATURES=$(echo ${JSON} | ${JQ} -r .identity.minimumsignatures)
    VERUSID_FRIENDLYNAME=$(echo ${JSON} | ${JQ} -r .identity.name)
    VERUSID_ZADDRESS=$(echo ${JSON} | ${JQ} -r .identity.privateaddress)
    VERUSID_TADDRESS=$(echo ${JSON} | ${JQ} -r .identity.primaryaddresses[] | xargs echo)

    eval "VERUSID_FRIENDLYNAME=${VERUSID_FRIENDLYNAME} VERUSID_REQUIRED_SIGNATURES=${VERUSID_REQUIRED_SIGNATURES} VERUSID_ZADDRESS=${VERUSID_ZADDRESS} VERUSID_TADDRESS=${VERUSID_TADDRESS}"
    [ ! -z ${VERUSID_FRIENDLYNAME} ] && return 0 || return 1
}

rpc_check(){
    USER=$1
    PASS=$2
    HOST=$3
    PORT=$4
	DATA=$(${CURL} -X POST -u ${USER}:${PASS} --data-binary \
    "{\"jsonrpc\": \"1.0\", \"id\": \"paperwallet\", \"method\": \"getmininginfo\"}" \
    -H 'content-type: application/json;' \
    http://${HOST}:${PORT} 2>/dev//null)
    
    [ ${?} -eq 7 ] && return 1 || return 0
}

paperwallet_balance(){
    BALANCE="${1}"
    BALANCE_INT=$(echo ${BALANCE} | cut -d'.' -f1)
    export BALANCE_DEC=$(echo ${BALANCE} | cut -d'.' -f2)
    export BALANCE_TEXT="$(./num2words "${BALANCE_INT}")"
    export BALANCE_INT=$(printf "%'.f" ${BALANCE_INT})
    CONTENT_BALANCE=$(envsubst < html/tpl/balance.tpl)
    echo "${CONTENT_BALANCE}"
}

paperwallet(){
    export ADDRESS="${1}"
    export KEY="${2}"
    export BALANCE="${3}"
    export NOTES="${4}"
    SHOW_BALANCE=${5}
    export TEMPLATE="${6}"
    export DATE="$(date '+%F %T %Z')"
    export SVG_KEY=$(get_qr_svg "${KEY}")
    export SVG_ADDRESS=$(get_qr_svg "${ADDRESS}")

    

   export CONTENT_BALANCE=""
   [ ${SHOW_BALANCE} -eq 1 ] && export CONTENT_BALANCE=$(paperwallet_balance "${BALANCE}")
    
    echo "$(envsubst < html/tpl/${TEMPLATE}.tpl)"
}

#paperwallet_verusid "${ADDRESS}" "${VERUSID_FRIENDLYNAME}" "${VERUSID_ZADDRESS}" "${VERUSID_TADDRESS}" "${VERUSID_REQUIRED_SIGNATURES}" "${NOTES}" "${BALANCE}" ${SHOW_BALANCE}
paperwallet_verusid(){
    export ADDRESS="${1}"
    export VERUSID_FRIENDLYNAME="${2}"
    export VERUSID_ZADDRESS="${3}"
    export VERUSID_TADDRESS=$(echo "${4}" | sed -s 's/ /, /g')
    export VERUSID_REQUIRED_SIGNATURES=${5}
    export NOTES="${6}"
    export BALANCE="${7}"
    SHOW_BALANCE=${8}
    export DATE="$(date '+%F %T %Z')"
    export SVG_VERUSID=$(get_qr_svg "${ADDRESS}")


    # add number of signatures to comment if > 1
    [ "${VERUSID_REQUIRED_SIGNATURES}" -gt 1 ] && {
        NOTES="Required number of signatures for \"${VERUSID_FRIENDLYNAME}\": <b>${VERUSID_REQUIRED_SIGNATURES} ($(./num2words ${VERUSID_REQUIRED_SIGNATURES}))</b><br />${NOTES}"
    }

   export CONTENT_BALANCE=""
    if [ ${SHOW_BALANCE} -eq 1 ]; then
        export CONTENT_BALANCE=$(paperwallet_balance "${BALANCE}")
    fi

    export CONTENT_WALLET=$(envsubst < html/tpl/verusid.tpl)
    echo "${CONTENT_WALLET}"

}

create_html_paperwallet(){
    SCAFFOLD="${1}"
    export CONTENT="${2}"
    OUTFILE="${3}"

    # css stuff
    export MASTER_CSS="$(cat html/css/master.css)"
    export GEOMANIST="$(cat html/css/geomanist.css)"
    envsubst < "${SCAFFOLD}" > "${OUTFILE}"
}

ADDRESS_TYPE=$(echo ${ADDRESS} | cut -c1)

case "${ADDRESS_TYPE}" in
    "R")
        TEMPLATE="t-encrypted"
        ;;
    "z")
        TEMPLATE="z-encrypted"
        ;;
    "i")
        TEMPLATE="verusid"
        ;;
esac

[ "${MODE}" == "daemon" ] && {
    rpc_check "${RPCUSER}" "${RPCPASS}" "${RPCHOST}" "${RPCPORT}"
    [ ${?} -eq 1 ] && {
        echo "ERROR: RPC interface error. Check host, port, user and password. Exiting!"
        exit 1
    }
    case "${ADDRESS_TYPE}" in
        "i")
            rpc_isvalid "${RPCUSER}" "${RPCPASS}" "${RPCHOST}" "${RPCPORT}" "${ADDRESS}"
            [ ${?} ] && {
                rpc_getidentity "${RPCUSER}" "${RPCPASS}" "${RPCHOST}" "${RPCPORT}" "${ADDRESS}"
            }
            ;;
        "R")
            rpc_isvalid "${RPCUSER}" "${RPCPASS}" "${RPCHOST}" "${RPCPORT}" "${ADDRESS}"
            [ ${?} ] && {
                BALANCE=$(rpc_getbalance "${RPCUSER}" "${RPCPASS}" "${RPCHOST}" "${RPCPORT}" "${ADDRESS}")
                KEY=$(rpc_exportkey "${RPCUSER}" "${RPCPASS}" "${RPCHOST}" "${RPCPORT}" "${ADDRESS}")
            }
            ;;
        "z")
            rpc_isvalid_z "${RPCUSER}" "${RPCPASS}" "${RPCHOST}" "${RPCPORT}" "${ADDRESS}"
            [ ${?} ] && {
                BALANCE=$(rpc_getbalance_z "${RPCUSER}" "${RPCPASS}" "${RPCHOST}" "${RPCPORT}" "${ADDRESS}")
                KEY=$(rpc_exportkey_z "${RPCUSER}" "${RPCPASS}" "${RPCHOST}" "${RPCPORT}" "${ADDRESS}")
            }
            ;;
        *)
            echo "ERROR: Unknown address type for ${ADDRESS}"
            exit 1
            ;;
    esac
}

[ "${ENCRYPT_KEY}" -eq 1 ] && {
    if [ "${TEMPLATE}" != "verusid" ] && [ -z "${PASSPHRASE}" ]; then
        echo "Encryption requested but no passphrase set. exiting."
        exit 1
    fi
    # counter: ${OPENSSL} enc -d -aes-256-cbc -a -salt -pbkdf2 -A -k "${PASSPHRASE}"
    KEY=$(echo "${KEY}" | ${OPENSSL} enc -e -aes-256-cbc -a -salt -pbkdf2 -A -k "${PASSPHRASE}")
} || {
    case "${ADDRESS_TYPE}" in
    "R")
        TEMPLATE="t-plain"
        ;;
    "z")
        TEMPLATE="z-plain"
        ;;
    esac
}

case "${TEMPLATE}" in
    "verusid")
        PAPERWALLET_SOURCE="$(paperwallet_verusid "${ADDRESS}" "${VERUSID_FRIENDLYNAME}" "${VERUSID_ZADDRESS}" "${VERUSID_TADDRESS}" "${VERUSID_REQUIRED_SIGNATURES}" "${NOTES}" "${BALANCE}" ${SHOW_BALANCE})"
        ;;
    *)
        PAPERWALLET_SOURCE="$(paperwallet "${ADDRESS}" "${KEY}" "${BALANCE}" "${NOTES}" ${SHOW_BALANCE} "${TEMPLATE}")"
        ;;
esac

create_html_paperwallet "html/tpl/paperwallet.tpl" "${PAPERWALLET_SOURCE}" "${OUTFILE}" && {
    echo "DONE! see ${OUTFILE}"
} || {
    echo "ERROR!"
}

##
# proper cleanup
##
unset ADDRESS KEY 
unset BALANCE BALANCE_DEC BALANCE_TEXT BALANCE_INT 
unset NOTES DATE 
unset SVG_KEY SVG_ADDRESS SVG_VERUSID
unset VERUSID_FRIENDLYNAME VERUSID_REQUIRED_SIGNATURES VERUSID_TADDRESS VERUSID_ZADDRESS  
unset CONTENT CONTENT_BALANCE CONTENT_WALLET CONTENT
unset TEMPLATE MASTER_CSS GEOMANIST

# EOF